# Copyright (c) 2026 Carter Spangler
# Licensed under the MIT License. 
# See LICENSE file in the project root for full license information.

# this module is entirely AI generated by Claude AI

from typing import List, Dict, Optional, Tuple
import tkinter as tk
from tkinter import ttk


def create_sheet_selection_gui(sheets: List[Dict]) -> Tuple[Optional[float], Optional[float]]:
    """Display a sheet selection window and return (width, height) in mm.
    
    Returns (None, None) if the user closes without selecting.
    """
    selected = {"width": None, "height": None}

    root = tk.Tk()
    root.title("Select Sheet")
    root.resizable(False, False)

    tk.Label(root, text="Select sheet size:").pack(padx=12, pady=(12, 4))

    sheet_names = [s["name"] for s in sheets]
    combo = ttk.Combobox(root, values=sheet_names, state="readonly", width=30)
    combo.pack(padx=12, pady=4)
    if sheet_names:
        combo.current(0)

    # manual override fields
    frame = tk.Frame(root)
    frame.pack(padx=12, pady=4)
    tk.Label(frame, text="Width (mm):").grid(row=0, column=0, sticky="e")
    width_var = tk.StringVar()
    width_entry = tk.Entry(frame, textvariable=width_var, width=10)
    width_entry.grid(row=0, column=1, padx=4)

    tk.Label(frame, text="Height (mm):").grid(row=1, column=0, sticky="e")
    height_var = tk.StringVar()
    height_entry = tk.Entry(frame, textvariable=height_var, width=10)
    height_entry.grid(row=1, column=1, padx=4)

    def _on_select(event=None):
        idx = combo.current()
        if idx >= 0:
            width_var.set(str(sheets[idx]["width"]))
            height_var.set(str(sheets[idx]["height"]))

    combo.bind("<<ComboboxSelected>>", _on_select)
    _on_select()  # populate fields from default selection

    def _on_confirm():
        try:
            selected["width"] = float(width_var.get())
            selected["height"] = float(height_var.get())
        except ValueError:
            tk.messagebox.showerror("Invalid input", "Width and height must be numbers.")
            return
        root.destroy()

    def _on_cancel():
        root.destroy()

    btn_frame = tk.Frame(root)
    btn_frame.pack(pady=(4, 12))
    tk.Button(btn_frame, text="Confirm", width=10, command=_on_confirm).pack(side="left", padx=4)
    tk.Button(btn_frame, text="Cancel", width=10, command=_on_cancel).pack(side="left", padx=4)

    root.mainloop()
    return selected["width"], selected["height"]